version: "3"
services:
  frontend:
    tty: true
    command: npm start
    container_name: basic-health-units-plataform
    build: ./
    ports:
      - 8000:8000
    volumes:
      - ../:/var/www/html/basic-health-units-plataform